services:
 
  db:
    env_file: .env 
    image: postgres:17-alpine 
    volumes:
      - ./data_apps_base/db:/var/lib/postgresql/data 
    environment: 
      POSTGRES_DB: ${DB_NAME} 
      POSTGRES_USER: ${DB_USER}    
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
    ports:
      - "5433:5432" 
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 25s
      timeout: 25s
      retries: 5
    
  backend:
    build: .
    ports:
      - "8000:8000"    
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on: 
      db:
        condition: service_healthy 
    volumes:
      - .:/app 

volumes:
  postgres_data: 